export type Tema = "cyberpunk" | "dnd";

const CYBERPUNK_SYSTEM_PROMPT = `Sen bir cyberpunk FRP oyununun anlatıcısısın (Game Master). Görevin, oyuncuyu daha ilk satırda içine çeken, olay örgüsü güçlü bir başlangıç sahnesi yazmak ve bunu yalnızca geçerli bir JSON nesnesi olarak döndürmek.

Dünya, neon ışıklarının yağmurda dağıldığı bir mega-şehir. Şehri mega-şirketler yönetiyor; implantlar ve yapay zekâ sıradanlaşmış, eşitsizlik bir uçuruma dönüşmüş. Ton karanlık, gergin ve teknolojik.

Sahne çoktan akmakta olan bir olayın tam ortası olsun. Oyuncu olayın içinde, bir eşiğin üzerinde durur.

"oyuncu_metni": ikinci tekil şahısla, 2-3 cümle. Eyleme davetle BİTMEZ.
"atmosfer", "olay_orgusu", "ana_gorev": yalnızca sistem içindir, oyuncu görmez.
"resim_promptu": 5-8 kelimelik İngilizce sahne etiketi. Örnek: "rooftop market, rain, neon signs".

Çıktı: yalnızca JSON, Türkçe (resim_promptu hariç), şemaya birebir uy.`;

const DND_SYSTEM_PROMPT = `Sen bir D&D fantezi FRP oyununun Dungeon Master'ısın. Görevin, oyuncuyu daha ilk satırda içine çeken, olay örgüsü güçlü bir başlangıç sahnesi yazmak ve bunu yalnızca geçerli bir JSON nesnesi olarak döndürmek.

Dünya, orta çağ fantasisi: krallıklar, ejderhalar, zindanlar, büyü ve tehlike. Ton karanlık, epik ve gizemli. Meşale ışığı, taş duvarlar, antik büyü ve bilinmeyenin korkusu hâkimdir.

Sahne çoktan akmakta olan bir olayın tam ortası olsun. Oyuncu olayın içinde, bir eşiğin üzerinde durur.

"oyuncu_metni": ikinci tekil şahısla, 2-3 cümle. Eyleme davetle BİTMEZ.
"atmosfer", "olay_orgusu", "ana_gorev": yalnızca sistem içindir, oyuncu görmez.
"resim_promptu": 5-8 kelimelik İngilizce sahne etiketi. Örnek: "torch-lit dungeon, ancient runes, shadowy corridor".

Çıktı: yalnızca JSON, Türkçe (resim_promptu hariç), şemaya birebir uy.`;

export function getSystemPrompt(tema: Tema): string {
  return tema === "dnd" ? DND_SYSTEM_PROMPT : CYBERPUNK_SYSTEM_PROMPT;
}

export const WORLD_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    atmosfer: {
      type: "object",
      additionalProperties: false,
      properties: {
        mekan: { type: "string", description: "Sahnenin geçtiği yer." },
        zaman: { type: "string", description: "Günün hangi vakti / koşullar." },
        ton: { type: "string", description: "Tek kelime veya kısa ifade." },
        betimleme: { type: "string", description: "Duyusal betimleme." },
      },
      required: ["mekan", "zaman", "ton", "betimleme"],
    },
    olay_orgusu: {
      type: "object",
      additionalProperties: false,
      properties: {
        durum: { type: "string", description: "Mevcut tehdit veya dengesizlik." },
        oyuncunun_konumu: { type: "string", description: "Oyuncu bu olayın neresinde?" },
        gizem: { type: "string", description: "Cevaplanmamış bir soru." },
      },
      required: ["durum", "oyuncunun_konumu", "gizem"],
    },
    ana_gorev: {
      type: "object",
      additionalProperties: false,
      properties: {
        hedef: { type: "string", description: "Net, somut hedef." },
        neden_acil: { type: "string", description: "Görev neden acil?" },
        ilk_adim: { type: "string", description: "Oyuncunun ilk somut adımı." },
        gorev_ozeti: { type: "string", description: "Tek cümlelik görev özeti." },
      },
      required: ["hedef", "neden_acil", "ilk_adim", "gorev_ozeti"],
    },
    oyuncu_metni: {
      type: "string",
      description: "Oyuncuya gösterilecek anlatı. 2-3 cümle, ikinci tekil şahıs. Eyleme davetle BİTMEZ.",
    },
    resim_promptu: {
      type: "string",
      description: "5-8 word English scene tag for image generation.",
    },
  },
  required: ["atmosfer", "olay_orgusu", "ana_gorev", "oyuncu_metni", "resim_promptu"],
} as const;

export interface World {
  atmosfer: { mekan: string; zaman: string; ton: string; betimleme: string };
  olay_orgusu: { durum: string; oyuncunun_konumu: string; gizem: string };
  ana_gorev: { hedef: string; neden_acil: string; ilk_adim: string; gorev_ozeti: string };
  oyuncu_metni: string;
  resim_promptu: string;
  // Injected by the route before storing — not generated by the model.
  tema?: Tema;
}

export function summarizeWorld(world: World): string {
  return [
    `Mekan: ${world.atmosfer.mekan}`,
    `Zaman: ${world.atmosfer.zaman}`,
    `Ton: ${world.atmosfer.ton}`,
    `Durum: ${world.olay_orgusu.durum}`,
    `Gizem: ${world.olay_orgusu.gizem}`,
    `Ana görev: ${world.ana_gorev.gorev_ozeti}`,
  ].join("\n");
}
